// <auto-generated />
using System;
using Meducate.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Meducate.Infrastructure.Migrations
{
    [DbContext(typeof(MeducateDbContext))]
    [Migration("20260218200356_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MeducateAPI.Models.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashedSecret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KeyId")
                        .IsUnique();

                    b.HasIndex("OrganisationId");

                    b.ToTable("ApiClients");
                });

            modelBuilder.Entity("MeducateAPI.Models.ApiUsageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("OrganisationName")
                        .HasColumnType("text");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId", "Timestamp");

                    b.ToTable("ApiUsageLogs");
                });

            modelBuilder.Entity("MeducateAPI.Models.HealthTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<string>("Actions")
                        .HasColumnType("jsonb");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<string>("Citations")
                        .HasColumnType("jsonb");

                    b.PrimitiveCollection<string>("Factors")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastSourceRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("NeedsLlmReprocessing")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<string>("Observations")
                        .HasColumnType("jsonb");

                    b.Property<string>("RawSource")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("Tags")
                        .HasColumnType("jsonb");

                    b.Property<string>("TopicType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("TopicType");

                    b.ToTable("HealthTopics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Actions = "[\"Short-acting bronchodilators (salbutamol)\",\"Inhaled corticosteroids\",\"Long-acting beta-agonists (LABAs)\",\"Leukotriene receptor antagonists\",\"Allergen avoidance strategies\"]",
                            Category = "Respiratory",
                            Citations = "[\"NICE Guideline NG80 \\u2013 Asthma: diagnosis, monitoring and chronic asthma management\",\"British Thoracic Society / SIGN \\u2013 British guideline on the management of asthma\"]",
                            Factors = "[\"Genetic predisposition\",\"Allergens (pollen, dust mites, pet dander)\",\"Respiratory infections in childhood\",\"Air pollution\",\"Occupational irritants\"]",
                            LastUpdated = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Asthma",
                            NeedsLlmReprocessing = false,
                            Observations = "[\"Wheezing\",\"Shortness of breath\",\"Chest tightness\",\"Coughing (especially at night or early morning)\",\"Difficulty breathing during exercise\"]",
                            Summary = "A chronic respiratory condition characterised by inflammation and narrowing of the airways, leading to recurrent episodes of wheezing, breathlessness, chest tightness, and coughing.",
                            Tags = "[\"chronic\",\"airways\",\"inflammation\",\"common\"]",
                            TopicType = "Disease",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Actions = "[\"Lifestyle modifications (diet and exercise)\",\"Metformin\",\"SGLT2 inhibitors (e.g. dapagliflozin)\",\"GLP-1 receptor agonists (e.g. semaglutide)\",\"Insulin therapy (if required)\"]",
                            Category = "Endocrine",
                            Citations = "[\"NICE Guideline NG28 \\u2013 Type 2 diabetes in adults: management\",\"WHO \\u2013 Diabetes fact sheet\"]",
                            Factors = "[\"Obesity and excess body fat\",\"Physical inactivity\",\"Genetic predisposition\",\"Age (risk increases over 40)\",\"Ethnicity (higher risk in South Asian, African-Caribbean populations)\"]",
                            LastUpdated = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Type 2 Diabetes",
                            NeedsLlmReprocessing = false,
                            Observations = "[\"Increased thirst (polydipsia)\",\"Frequent urination (polyuria)\",\"Unexplained weight loss\",\"Fatigue\",\"Blurred vision\",\"Slow-healing wounds\"]",
                            Summary = "A metabolic disorder characterised by insulin resistance and relative insulin deficiency, resulting in chronic hyperglycaemia. It is strongly associated with obesity and physical inactivity.",
                            Tags = "[\"chronic\",\"metabolic\",\"common\",\"lifestyle\"]",
                            TopicType = "Disease",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Actions = "[\"Lifestyle changes (reduced salt, exercise, weight loss)\",\"ACE inhibitors (e.g. ramipril)\",\"Calcium channel blockers (e.g. amlodipine)\",\"Thiazide-like diuretics (e.g. indapamide)\",\"Angiotensin II receptor blockers (e.g. losartan)\"]",
                            Category = "Cardiovascular",
                            Citations = "[\"NICE Guideline NG136 \\u2013 Hypertension in adults: diagnosis and management\",\"ESC/ESH 2018 Guidelines for the management of arterial hypertension\"]",
                            Factors = "[\"Excess dietary sodium\",\"Obesity\",\"Physical inactivity\",\"Excessive alcohol consumption\",\"Genetic factors\",\"Chronic stress\"]",
                            LastUpdated = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hypertension",
                            NeedsLlmReprocessing = false,
                            Observations = "[\"Usually asymptomatic (silent condition)\",\"Headaches (in severe cases)\",\"Visual disturbances\",\"Chest pain (hypertensive emergency)\",\"Nosebleeds (rare)\"]",
                            Summary = "Persistently elevated arterial blood pressure, typically defined as systolic ≥140 mmHg and/or diastolic ≥90 mmHg. A major risk factor for cardiovascular disease, stroke, and chronic kidney disease.",
                            Tags = "[\"chronic\",\"silent\",\"cardiovascular\",\"common\"]",
                            TopicType = "Disease",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Actions = "[\"Acute: triptans (e.g. sumatriptan)\",\"Acute: NSAIDs (e.g. ibuprofen, aspirin)\",\"Preventive: beta-blockers (e.g. propranolol)\",\"Preventive: topiramate\",\"CGRP monoclonal antibodies (e.g. erenumab)\"]",
                            Category = "Neurological",
                            Citations = "[\"NICE Guideline CG150 \\u2013 Headaches in over 12s: diagnosis and management\",\"The Migraine Trust \\u2013 Clinical resources\"]",
                            Factors = "[\"Genetic predisposition\",\"Hormonal changes (e.g. menstruation)\",\"Stress and anxiety\",\"Certain foods (aged cheese, alcohol, caffeine)\",\"Sleep disturbances\"]",
                            LastUpdated = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Migraine",
                            NeedsLlmReprocessing = false,
                            Observations = "[\"Severe throbbing headache (often unilateral)\",\"Nausea and vomiting\",\"Photophobia (sensitivity to light)\",\"Phonophobia (sensitivity to sound)\",\"Aura (visual disturbances, tingling) in some patients\"]",
                            Summary = "A primary headache disorder characterised by recurrent episodes of moderate to severe unilateral throbbing headache, often accompanied by nausea, vomiting, and sensitivity to light and sound.",
                            Tags = "[\"episodic\",\"headache\",\"neurological\",\"common\"]",
                            TopicType = "Disease",
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Actions = "[\"Cognitive behavioural therapy (CBT)\",\"Selective serotonin reuptake inhibitors (SSRIs, e.g. sertraline)\",\"Serotonin-noradrenaline reuptake inhibitors (SNRIs)\",\"Physical exercise programmes\",\"Mindfulness-based cognitive therapy\"]",
                            Category = "Mental Health",
                            Citations = "[\"NICE Guideline NG222 \\u2013 Depression in adults: treatment and management\",\"WHO \\u2013 Depression fact sheet\"]",
                            Factors = "[\"Biological factors (neurotransmitter imbalances)\",\"Genetic predisposition\",\"Traumatic or stressful life events\",\"Chronic illness\",\"Social isolation\"]",
                            LastUpdated = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Depression",
                            NeedsLlmReprocessing = false,
                            Observations = "[\"Persistent low mood\",\"Loss of interest or pleasure (anhedonia)\",\"Fatigue and low energy\",\"Sleep disturbances (insomnia or hypersomnia)\",\"Changes in appetite or weight\",\"Difficulty concentrating\",\"Feelings of worthlessness or guilt\"]",
                            Summary = "A common mental health disorder characterised by persistent low mood, loss of interest or pleasure in activities, and a range of emotional and physical symptoms lasting at least two weeks.",
                            Tags = "[\"chronic\",\"mental health\",\"common\",\"mood disorder\"]",
                            TopicType = "Disease",
                            Version = 1
                        });
                });

            modelBuilder.Entity("MeducateAPI.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("MeducateAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerificationTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("VerificationToken");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MeducateAPI.Models.ApiClient", b =>
                {
                    b.HasOne("MeducateAPI.Models.Organisation", "Organisation")
                        .WithMany("ApiClients")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("MeducateAPI.Models.ApiUsageLog", b =>
                {
                    b.HasOne("MeducateAPI.Models.ApiClient", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("MeducateAPI.Models.Organisation", b =>
                {
                    b.HasOne("MeducateAPI.Models.User", "User")
                        .WithOne("Organisation")
                        .HasForeignKey("MeducateAPI.Models.Organisation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MeducateAPI.Models.Organisation", b =>
                {
                    b.Navigation("ApiClients");
                });

            modelBuilder.Entity("MeducateAPI.Models.User", b =>
                {
                    b.Navigation("Organisation");
                });
#pragma warning restore 612, 618
        }
    }
}
